apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-argo-pv-claim
  namespace: testjenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Replace with your dynamic storage class name if different
